main: tfmc.justin.gitstone.GitStonePlugin
version: 1.0.0
name: GitStone
author: Justin
api-version: 1.21

commands:
  gs:
    description: GitStone - GitHub for Minecraft builds
    usage: /gs <wand|init|use|list|pos1|pos2|sel|commit|status|log|branch|checkout|help>
    aliases: [gitstone]
    permission: gitstone.use

permissions:
  gitstone.use:
    description: Allows using GitStone commands
    default: op
